### ISSUE TITLE
Invert some windows only

### ISSUE THREAD

**Issue by b1f6c1c4** [zoltanp/xrandr-invert-colors#22]
Is it possible to invert some windows only?

**Comment by zoltanp** [comment]
With this utility, no, because of its design. xrandr-invert-colors works on screen connection level (VGA, HDMI, ...), it doesn't know anything about what is displayed on the screen.

Some window managers and compositors have support for inverting colors of a specific window. For example Compiz, KWin (from KDE), Compton.

See for example:

https://unix.stackexchange.com/questions/20565/invert-colors-of-the-active-window

https://askubuntu.com/questions/520207/how-do-i-invert-windows-colors-using-compiz/1064072

https://askubuntu.com/questions/134668/how-to-trigger-a-color-inversion-effect-for-one-window

**Comment by b1f6c1c4** [comment]
Thanks for the help. What I'm actually looking for is to get dark mode for all my entire screen, but simply inverting the screen, inverting some windows manually, or any kinds of manual inversion is not good enough for me. I've finally reached a solution by using FPGA to hack the HDMI signal. See my repo [Deep: Dark-Fantasy](https://github.com/b1f6c1c4/Deep-DarkFantasy) if you are interested.
